<?php

function bots_menu() {  
    $items['bots_view'] = array(
        'page callback' => 'menufun_bots_view',
		'access callback' => 'user_access',
		'access arguments' => array('view basic bot info'),
        'type' => MENU_CALLBACK,
    );
    $items['bots_data'] = array(
        'page callback' => 'menufun_bots_data',
		'access callback' => 'user_access',
		'access arguments' => array('view basic bot info'),
        'type' => MENU_CALLBACK,
    );
    $items['bots_data_edit'] = array(
        'page callback' => 'menufun_bots_data_edit',
		'access callback' => TRUE,
		//'access arguments' => array('Insert/Update bots data'),
        'type' => MENU_CALLBACK,
    );
	$items['admin/config/bots'] = array(
		'title' => 'Boryi',
		'description' => 'bots settings',
		'position' => 'right',
		'weight' => -5,
		'page callback' => 'system_admin_menu_block_page',
		'access arguments' => array('administer site configuration'),
		'file' => 'system.admin.inc',
		'file path' => drupal_get_path('module', 'system'),
	);
	$items['admin/config/bots/settings'] = array(
		'title' => 'Bots settings',
		'description' => 'Change bots settings.',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('bots_admin_settings'),
		'access arguments' => array('administer site configuration'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'bots.admin.inc',
	);
    return $items;
}



/**
* Implementation of hook_action_info().
*/
function bots_action_info() {
	return array(
		'beep_beep_action' => array(
			'type' => 'system',
			'label' => t('Beep annoyingly'),
			'configurable' => FALSE,
			'triggers' => array('node_view', 'node_insert', 'node_update', 'node_delete'),
		),
	);
}
/**
* Simulate a beep. A Drupal action.
*/
function bots_beep_action() {
	watchdog('beep', 'Beep!');
}


function menufun_bots_view(){
	module_load_include('inc', 'bots', 'inc/bots.view');
	return get_view();
}

function menufun_bots_data(){
	module_load_include('inc', 'bots', 'inc/bots.data');
	echo get_data();
	exit(0);
}

function menufun_bots_data_edit(){
	module_load_include('inc', 'bots', 'inc/bots.dataedit');
	echo get_data_edit();
	exit(0);
}

/**
 * Implements hook_permission().
 */
function bots_permission() {
  $permissions['view basic bot info'] = array(
    'title' => t('View basic bot info'),
    'description' => t('Allow users to view basic bot info'),
  );
  $permissions['edit bot info'] = array(
    'title' => t('Edit bot info'),
    'description' => t('Allow users to add/edit/delete bot info'),
  );
  return $permissions;
}